services:
  - type: web
    name: churn-prediction-api
    env: python
    region: singapore
    plan: free

    buildCommand: pip install -r churn-backend/requirements.txt
    startCommand: uvicorn churn-backend.app:app --host 0.0.0.0 --port $PORT

    envVars:
      - key: PYTHON_VERSION
        value: 3.11
