services:
  - type: web
    name: churn-prediction-api
    env: python
    plan: free
    region: oregon

    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn churn_backend.app:app --host 0.0.0.0 --port $PORT

    envVars:
      - key: PYTHON_VERSION
        value: 3.11
